apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.db.name }}
  namespace: {{ .Release.Namespace }}
spec:
  enableSuperuserAccess: true  
  instances: 3
  storage:
    size: 1Gi
    storageClass: ceph-kubepv
    
  postgresql:
    pg_hba:
      - "host all all 0.0.0.0/0 md5"

  bootstrap:
    initdb:
      database: {{ .Values.db.database }}
      owner: {{ .Values.db.owner }}
      secret:
        name: {{ .Values.db.name }}-app-user
        
  superuserSecret:
    name: {{ .Values.db.name }}-dumb-su