apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.db.name }}-dumb-su"
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: postgres
  password: "{{ .Values.db.superuserPassword | default "postgres123" }}"