apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.db.name }}-server-cert
spec:
  secretName: {{ .Values.db.name }}-server-cert
  usages:
    - server auth
  dnsNames:
    - "{{ .Values.db.name }}.k8s.ucar.edu"
  issuerRef:
    name: incommon
    kind: ClusterIssuer
    group: cert-manager.io